# Generated by Django 6.0.5 on 2026-05-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0002_delete_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='Qampus.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='Qampus.post')),
            ],
        ),
    ]
