# Generated by Django 6.0.5 on 2026-05-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0003_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
