# Generated by Django 6.0.5 on 2026-05-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0004_alter_reply_options'),
        ('Qampus', '0004_remove_post_category_post_category'),
    ]

    operations = [
    ]
